import 'package:ShopyFast/domain/models/Product.dart';
import 'package:ShopyFast/utils/categoryConstants.dart';

class DummyData {
  static final List<Product> dummyListOfProduct = [
    Product(
        category: CategoriesConstant.FRUITS_AND_VEGETABLE,
        productName: 'vegetable',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'fruit_vegetable#vegetable#sid'),
    Product(
        category: CategoriesConstant.FRUITS_AND_VEGETABLE,
        productName: 'fruit',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'fruit_vegetable#fruit#sid'),
    Product(
        category: CategoriesConstant.GROCERY,
        productName: 'Aata',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'aata#435',
        weight: 3,
        subcategory: 'grocery#aata#sid'),
    Product(
        category: CategoriesConstant.GROCERY,
        productName: 'Dry Frits',
        description:
            'dry fruits is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'grocery#dryfruits#sid'),
    Product(
        category: CategoriesConstant.GROCERY,
        productName: 'Ghee Vanaspati',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'grocery#ghee_vanaspati#sid'),
    Product(
        category: CategoriesConstant.GROCERY,
        productName: 'Edible Oils',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'grocery#edible_oils#sid'),
    Product(
        category: CategoriesConstant.GROCERY,
        productName: 'Pulses',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'grocery#pulses#sid'),
    Product(
        category: CategoriesConstant.GROCERY,
        productName: 'Rice & Grains',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'grocery#rice_grains#sid'),
    Product(
        category: CategoriesConstant.GROCERY,
        productName: 'Salt and Sub',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'grocery#salt_sugar#sid'),
    Product(
        category: CategoriesConstant.GROCERY,
        productName: 'fruit',
        description: 'tomato is most used item, and contains most of vitamins',
        imageUrl: 'assets/images/categoryItems/chakki_aata.webp',
        measureUnit: 'Kg',
        price: 50.0,
        productId: 'tomato#435',
        weight: 3,
        subcategory: 'fruit_vegetable#vegetable#sid'),
  ];
}
